In [1]:
import pandas as pd
import joblib
import sys

sys.path.append('..')
from src.pipeline.inference import run_inference_pipeline

In [2]:
# ============================================================
# LOAD DATA AND MODEL
# ============================================================

df = pd.read_parquet("../data/processed/processed_dataset.parquet")

model = joblib.load(
    "../data/artifacts/random_forest_matcher.joblib"
)

print(f"Dataset rows: {len(df):,}")
print("Model loaded.")

Dataset rows: 3,653,581
Model loaded.

In [3]:
# ============================================================
# SAMPLE FOR FIRST FULL PIPELINE TEST
# ============================================================

# Для первого запуска берем sample.
# На всем датасете может быть слишком много кандидатов.

df_sample = df.sample(
    100_000,
    random_state=42,
)

print(f"Sample rows: {len(df_sample):,}")

Sample rows: 100,000

In [4]:
# ============================================================
# RUN INFERENCE PIPELINE
# ============================================================

scored_pairs = run_inference_pipeline(
    df=df_sample,
    model=model,
    max_block_size=500,
    score_threshold=0.5,
)

print(f"Scored candidate pairs: {len(scored_pairs):,}")

display(scored_pairs.head())

Scored candidate pairs: 2,865,301

,idx1,idx2,block_col,block_value,left,right,pair_key,record_id_1,party_public_id_1,party_name_1,...,same_country,same_script,same_relation_kind,same_relation_role,same_company_public_id,is_garbage_1,is_garbage_2,has_garbage_entity,duplicate_score,duplicate_prediction
0,1643829,1842118,block_prefix_len,aali_5,1643829,1842118,1643829_1842118,kgz_rec_7d014314377f9be6297c18e234d1e2c4,NaN,Аалиев Азамат Черикбекович,...,1,1,0,0,0,0,0,0,0.004004,0
1,1643829,1710283,block_prefix_len,aali_5,1643829,1710283,1643829_1710283,kgz_rec_7d014314377f9be6297c18e234d1e2c4,NaN,Аалиев Азамат Черикбекович,...,1,1,1,1,0,0,0,0,0.002000,0
2,1643829,2392318,block_prefix_len,aali_5,1643829,2392318,1643829_2392318,kgz_rec_7d014314377f9be6297c18e234d1e2c4,NaN,Аалиев Азамат Черикбекович,...,1,1,0,0,0,0,0,0,0.004004,0
3,1643829,1605889,block_prefix_len,aali_5,1605889,1643829,1605889_1643829,kgz_rec_7d014314377f9be6297c18e234d1e2c4,NaN,Аалиев Азамат Черикбекович,...,1,1,1,1,0,0,0,0,0.009948,0
4,1842118,1710283,block_prefix_len,aali_5,1710283,1842118,1710283_1842118,kgz_rec_9def59463050ad0cc86cc05d16611f9f,NaN,Аалиев Талдыбек Кемелович,...,1,1,0,0,0,0,0,0,0.012330,0

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
scored_pairs.head()

,idx1,idx2,block_col,block_value,left,right,pair_key,record_id_1,party_public_id_1,party_name_1,name_latin_1,name_no_legal_1,country_1,script_1,relation_kind_1,relation_role_1,company_public_id_1,company_name_norm_1,record_id_2,party_public_id_2,party_name_2,name_latin_2,name_no_legal_2,country_2,script_2,relation_kind_2,relation_role_2,company_public_id_2,company_name_norm_2,fuzz_ratio,partial_ratio,token_sort_ratio,token_set_ratio,exact_match,token_jaccard,common_tokens,len_1,len_2,length_diff,token_count_1,token_count_2,token_count_diff,has_legal_form_1,has_legal_form_2,same_legal_form,core_fuzz_ratio,core_token_sort_ratio,core_token_set_ratio,core_exact_match,same_country,same_script,same_relation_kind,same_relation_role,same_company_public_id,is_garbage_1,is_garbage_2,has_garbage_entity,duplicate_score,duplicate_prediction
0,1643829,1842118,block_prefix_len,aali_5,1643829,1842118,1643829_1842118,kgz_rec_7d014314377f9be6297c18e234d1e2c4,NaN,Аалиев Азамат Черикбекович,aaliev azamat cherikbekovich,аалиев азамат черикбекович,kgz,cyrillic,director,director,kgz_company_3acb9c1e3816279c,азамат финанс жоопкерчилиги чектелген коому,kgz_rec_9def59463050ad0cc86cc05d16611f9f,NaN,Аалиев Талдыбек Кемелович,aaliev taldybek kemelovich,аалиев талдыбек кемелович,kgz,cyrillic,shareholder,founder,kgz_company_b4a741e494b9f7a1,булак кенч жоопкерчилиги чектелген коому,59.259259,53.846154,51.851852,51.851852,0,0.2,1,28,26,2,3,3,0,0,0,1,59.259259,51.851852,51.851852,0,1,1,0,0,0,0,0,0,0.004004,0
1,1643829,1710283,block_prefix_len,aali_5,1643829,1710283,1643829_1710283,kgz_rec_7d014314377f9be6297c18e234d1e2c4,NaN,Аалиев Азамат Черикбекович,aaliev azamat cherikbekovich,аалиев азамат черикбекович,kgz,cyrillic,director,director,kgz_company_3acb9c1e3816279c,азамат финанс жоопкерчилиги чектелген коому,kgz_rec_3e7e4d148bd4c7c02935f69e6593fe93,NaN,Аалиев Бактыбек Аалиевич,aaliev baktybek aalievich,аалиев бактыбек аалиевич,kgz,cyrillic,director,director,kgz_company_8a466d9eddbbf180,сэйф бизнес жоопкерчилиги чектелген коому,60.377358,58.536585,56.603774,56.603774,0,0.2,1,28,25,3,3,3,0,0,0,1,60.377358,56.603774,56.603774,0,1,1,1,1,0,0,0,0,0.002000,0
2,1643829,2392318,block_prefix_len,aali_5,1643829,2392318,1643829_2392318,kgz_rec_7d014314377f9be6297c18e234d1e2c4,NaN,Аалиев Азамат Черикбекович,aaliev azamat cherikbekovich,аалиев азамат черикбекович,kgz,cyrillic,director,director,kgz_company_3acb9c1e3816279c,азамат финанс жоопкерчилиги чектелген коому,kgz_rec_c921a1dc6b8b86f6487bb8d7f077aadd,NaN,Аалиев Жаныбек Маметович,aaliev zhanybek mametovich,аалиев жаныбек маметович,kgz,cyrillic,shareholder,founder,kgz_company_b2dc25c9b48a0f79,берик курулуш жоопкерчилиги чектелген коому,62.962963,66.666667,55.555556,55.555556,0,0.2,1,28,26,2,3,3,0,0,0,1,62.962963,55.555556,55.555556,0,1,1,0,0,0,0,0,0,0.004004,0
3,1643829,1605889,block_prefix_len,aali_5,1605889,1643829,1605889_1643829,kgz_rec_7d014314377f9be6297c18e234d1e2c4,NaN,Аалиев Азамат Черикбекович,aaliev azamat cherikbekovich,аалиев азамат черикбекович,kgz,cyrillic,director,director,kgz_company_3acb9c1e3816279c,азамат финанс жоопкерчилиги чектелген коому,kgz_rec_5f4e64b6e43ce3b885567621dc5eda31,NaN,Аалиев Бакытбек Белекович,aaliev bakytbek belekovich,аалиев бакытбек белекович,kgz,cyrillic,director,director,kgz_company_8fac66b3030e5ba4,белек тур интернэшнл жоопкерчилиги чектелген к...,70.370370,65.384615,70.370370,70.370370,0,0.2,1,28,26,2,3,3,0,0,0,1,70.370370,70.370370,70.370370,0,1,1,1,1,0,0,0,0,0.009948,0
4,1842118,1710283,block_prefix_len,aali_5,1710283,1842118,1710283_1842118,kgz_rec_9def59463050ad0cc86cc05d16611f9f,NaN,Аалиев Талдыбек Кемелович,aaliev taldybek kemelovich,аалиев талдыбек кемелович,kgz,cyrillic,shareholder,founder,kgz_company_b4a741e494b9f7a1,булак кенч жоопкерчилиги чектелген коому,kgz_rec_3e7e4d148bd4c7c02935f69e6593fe93,NaN,Аалиев Бактыбек Аалиевич,aaliev baktybek aalievich,аалиев бактыбек аалиевич,kgz,cyrillic,director,director,kgz_company_8a466d9eddbbf180,сэйф бизнес жоопкерчилиги чектелген коому,70.588235,68.000000,70.588235,70.588235,0,0.2,1,26,25,1,3,3,0,0,0,1,70.588235,70.588235,70.588235,0,1,1,0,0,0,0,0,0,0.012330,0

In [7]:
# ============================================================
# SCORE DISTRIBUTION
# ============================================================

print(scored_pairs["duplicate_score"].describe())

print("\nPredictions:")
print(scored_pairs["duplicate_prediction"].value_counts())

count    2.865301e+06
mean     1.306224e-01
std      2.797059e-01
min      2.687838e-06
25%      2.638462e-04
50%      9.680313e-03
75%      1.134590e-01
max      1.000000e+00
Name: duplicate_score, dtype: float64

Predictions:
duplicate_prediction
0    2608794
1     256507
Name: count, dtype: int64

In [8]:
# ============================================================
# TOP DUPLICATE CANDIDATES
# ============================================================

top_duplicates = (
    scored_pairs
    .sort_values("duplicate_score", ascending=False)
    .head(50)
)

display(
    top_duplicates[
        [
            "party_name_1",
            "party_name_2",
            "name_latin_1",
            "name_latin_2",
            "duplicate_score",
            "duplicate_prediction",
        ]
    ]
)

,party_name_1,party_name_2,name_latin_1,name_latin_2,duplicate_score,duplicate_prediction
1313674,Համադ Բինխալիֆա Բինհամադ Ալ-Թանի,Համադ Բինխալիֆ Բինհամադ Ալ-Թանի,hamad binkhalifa binhamad al tani,hamad binkhalif binhamad al tani,1.000000,1
1313675,Համադ Բինխալիֆա Բինհամադ Ալ-Թանի,Համադ Բինխալիֆ Բինհամադ Ալ-Թանի,hamad binkhalifa binhamad al tani,hamad binkhalif binhamad al tani,1.000000,1
1313664,Համադ Բինխալիֆ Բինհամադ Ալ-Թանի,Համադ Բինխալիֆա Բինհամադ Ալ-Թանի,hamad binkhalif binhamad al tani,hamad binkhalifa binhamad al tani,1.000000,1
1313669,Համադ Բինխալիֆ Բինհամադ Ալ-Թանի,Համադ Բինխալիֆա Բինհամադ Ալ-Թանի,hamad binkhalif binhamad al tani,hamad binkhalifa binhamad al tani,1.000000,1
1313676,Համադ Բինխալիֆա Բինհամադ Ալ-Թանի,Համադ Բինխալիֆ Բինհամադ Ալ-Թանի,hamad binkhalifa binhamad al tani,hamad binkhalif binhamad al tani,1.000000,1
1849270,ՄՈՐԻՑ ՋՀՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,ՄՈՐԻՑ ՋՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,morits jhonatan hieronimous hill,morits jonatan hieronimous hill,1.000000,1
1849269,ՄՈՐԻՑ ՋՀՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,ՄՈՐԻՑ ՋՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,morits jhonatan hieronimous hill,morits jonatan hieronimous hill,1.000000,1
1849268,ՄՈՐԻՑ ՋՀՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,ՄՈՐԻՑ ՋՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,morits jhonatan hieronimous hill,morits jonatan hieronimous hill,1.000000,1
1849271,ՄՈՐԻՑ ՋՀՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,ՄՈՐԻՑ ՋՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,morits jhonatan hieronimous hill,morits jonatan hieronimous hill,1.000000,1
1849272,ՄՈՐԻՑ ՋՀՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,ՄՈՐԻՑ ՋՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,morits jhonatan hieronimous hill,morits jonatan hieronimous hill,1.000000,1
2864095,өлзийсайхан батсайхан,Батсайхан Өлзийсайхан,olzii sai han batsai han,batsai han olzii sai han,1.000000,1
2436494,Тилекматова Чинара Асанкожоевна,Тилекматова Чинара Асанкожоева,tilekmatova chinara asankozhoevna,tilekmatova chinara asankozhoeva,0.999999,1
79125,Ахмедов Иномжан Абдуллажанович,Ахмедов Иномжан Абдулажанович,ahmedov inomzhan abdullazhanovich,ahmedov inomzhan abdulazhanovich,0.999999,1
2405158,Таласбаев Бактыбек Иманкулович,Таласбаев Бактыбек Исманкулович,talasbaev baktybek imankulovich,talasbaev baktybek ismankulovich,0.999999,1
1649268,Министерство Здравохранения Кр,Министерство здравоохранения КР,ministerstvo zdravohraneniya kr,ministerstvo zdravoohraneniya kr,0.999999,1
1649267,Министерство Здравохранения Кр,Министерство здравоохранения КР,ministerstvo zdravohraneniya kr,ministerstvo zdravoohraneniya kr,0.999999,1
1649266,Министерство Здравохранения Кр,Министерство здравоохранения КР,ministerstvo zdravohraneniya kr,ministerstvo zdravoohraneniya kr,0.999999,1
2864730,энхсайхан сайхантуяа,Сайхантуяа Энхсайхан,enhsai han sai hantuyaa,sai hantuyaa enhsai han,0.999999,1
2864232,Мэндсайхан Баярсайхан,баярсайхан мэндсайхан,mendsai han bayarsai han,bayarsai han mendsai han,0.999999,1
2864231,Баярсайхан Мэндсайхан,Мэндсайхан Баярсайхан,bayarsai han mendsai han,mendsai han bayarsai han,0.999999,1
2436488,Тилекматова Чинара Асанкожоевна,Тилекматова Чинара Асанкожоева,tilekmatova chinara asankozhoevna,tilekmatova chinara asankozhoeva,0.999999,1
1558171,Маматов Замирбек Мурзапаашаевич,Маматов Замирбек Музапаашаевич,mamatov zamirbek murzapaashaevich,mamatov zamirbek muzapaashaevich,0.999999,1
2317394,Шаршебаев Эдил Талантбекович,Шаршенбаев Эдил Талантбекович,sharshebaev edil talantbekovich,sharshenbaev edil talantbekovich,0.999999,1
570799,Баярмаа Баярсайхан,Баяраа Баярсайхан,bayarmaa bayarsai han,bayaraa bayarsai han,0.999999,1
2624285,Заварзин Юрий Тимофеевич,Заварин Юрий Тимофеевич,zavarzin yurii timofeevich,zavarin yurii timofeevich,0.999998,1
2624276,Заварзин Юрий Тимофеевич,Заварин Юрий Тимофеевич,zavarzin yurii timofeevich,zavarin yurii timofeevich,0.999998,1
2439039,Тохтакунов Марат Талгатович,Тохтахунов Марат Талгатович,tohtakunov marat talgatovich,tohtahunov marat talgatovich,0.999997,1
2584554,Ульмасов Олимжан Махмутович,Ульмасов Олымжан Махмутович,ulmasov olimzhan mahmutovich,ulmasov olymzhan mahmutovich,0.999997,1
2335863,СТРИНЖА СЕРГЕЙ СЕРГЕЕВИЧ,Стрижак Сергей Сергеевич,strinzha sergei sergeevich,strizhak sergei sergeevich,0.999997,1
64219,Абышов Омур Абылмечинович,Абышов Ɵмүр Абылмечинович,abyshov omur abylmechinovich,abyshov ɵmur abylmechinovich,0.999997,1
2411231,Թեղուտ Ինվեստմենտս Լիմիթիդ,Թեղուտ ինվեստմենտս Լիմիթեդ,teghout investments limitid,teghout investments limited,0.999997,1
2411232,Թեղուտ Ինվեստմենտս Լիմիթիդ,Թեղուտ ինվեստմենտս Լիմիթեդ,teghout investments limitid,teghout investments limited,0.999997,1
2584555,Ульмасов Олимжан Махмутович,Ульмасов Олымжан Махмутович,ulmasov olimzhan mahmutovich,ulmasov olymzhan mahmutovich,0.999997,1
2327876,согласно реестру 38 акционеров,Согласно Реестра Акционеров,soglasno reestru aktsionerov,soglasno reestra aktsionerov,0.999997,1
285232,Артыкбаев Субанбек Мамбетжанович,Артыкбаев Суранбек Мамбетжанович,artykbaev subanbek mambetzhanovich,artykbaev suranbek mambetzhanovich,0.999997,1
2289989,САтыбалдыев Рахманали Мансурович,Сатыбалдиев Рахманали Мансурович,satybaldyev rahmanali mansurovich,satybaldiev rahmanali mansurovich,0.999997,1
2624287,Заварин Юрий Тимофеевич,Заварзин Юрий Тимофеевич,zavarin yurii timofeevich,zavarzin yurii timofeevich,0.999996,1
1461404,Карыпбек уулу Улукбек,Карыбек уулу Улукбек,karypbek uulu ulukbek,karybek uulu ulukbek,0.999995,1
2250483,Рысбеков Эсен Уланбеколвич,Рысбеков Эсен Уланбекович,rysbekov esen ulanbekolvich,rysbekov esen ulanbekovich,0.999994,1
64231,Абышкаев Данияр Молдакунович,Абышкаев Данияр Молакунович,abyshkaev daniyar moldakunovich,abyshkaev daniyar molakunovich,0.999993,1
1313572,Халыков Ибрагим Мамажакыпович,Халыков Ибраим Мамажакыпович,halykov ibragim mamazhakypovich,halykov ibraim mamazhakypovich,0.999993,1
2863918,Bai Siqin,Siqin Bai,bai siqin,siqin bai,0.999992,1
2865294,WANG YUFEI,Yufei Wang,wang yufei,yufei wang,0.999992,1
2865278,цэнд туул,Туул Цэнд,tsend tuul,tuul tsend,0.999992,1
2864996,Икбал Салим,Салим Икбал,ikbal salim,salim ikbal,0.999992,1
2863917,Bai Siqin,Siqin Bai,bai siqin,siqin bai,0.999992,1
2865201,Okuno Reeko,Reeko Okuno,okuno reeko,reeko okuno,0.999992,1
2864285,Bin Huang,Huang Bin,bin huang,huang bin,0.999992,1
2863935,Хулан Бат,Бат Хулан,hulan bat,bat hulan,0.999992,1
2863725,Ta Ala,Ala Ta,ta ala,ala ta,0.999992,1

In [9]:
# ============================================================
# PREDICTED DUPLICATES ONLY
# ============================================================

predicted_duplicates = scored_pairs[
    scored_pairs["duplicate_prediction"] == 1
].copy()

print(f"Predicted duplicate pairs: {len(predicted_duplicates):,}")

display(
    predicted_duplicates[
        [
            "party_name_1",
            "party_name_2",
            "duplicate_score",
        ]
    ]
    .sort_values("duplicate_score", ascending=False)
    .head(50)
)

Predicted duplicate pairs: 256,507

,party_name_1,party_name_2,duplicate_score
1313664,Համադ Բինխալիֆ Բինհամադ Ալ-Թանի,Համադ Բինխալիֆա Բինհամադ Ալ-Թանի,1.000000
1313675,Համադ Բինխալիֆա Բինհամադ Ալ-Թանի,Համադ Բինխալիֆ Բինհամադ Ալ-Թանի,1.000000
1313674,Համադ Բինխալիֆա Բինհամադ Ալ-Թանի,Համադ Բինխալիֆ Բինհամադ Ալ-Թանի,1.000000
1313669,Համադ Բինխալիֆ Բինհամադ Ալ-Թանի,Համադ Բինխալիֆա Բինհամադ Ալ-Թանի,1.000000
1313676,Համադ Բինխալիֆա Բինհամադ Ալ-Թանի,Համադ Բինխալիֆ Բինհամադ Ալ-Թանի,1.000000
1849270,ՄՈՐԻՑ ՋՀՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,ՄՈՐԻՑ ՋՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,1.000000
1849269,ՄՈՐԻՑ ՋՀՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,ՄՈՐԻՑ ՋՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,1.000000
1849268,ՄՈՐԻՑ ՋՀՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,ՄՈՐԻՑ ՋՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,1.000000
1849272,ՄՈՐԻՑ ՋՀՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,ՄՈՐԻՑ ՋՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,1.000000
1849271,ՄՈՐԻՑ ՋՀՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,ՄՈՐԻՑ ՋՈՆԱԹԱՆ ՀԻԵՐՈՆԻՄՈՒՍ ՀԻԼԼ,1.000000
2864095,өлзийсайхан батсайхан,Батсайхан Өлзийсайхан,1.000000
2436494,Тилекматова Чинара Асанкожоевна,Тилекматова Чинара Асанкожоева,0.999999
1649268,Министерство Здравохранения Кр,Министерство здравоохранения КР,0.999999
1649267,Министерство Здравохранения Кр,Министерство здравоохранения КР,0.999999
1649266,Министерство Здравохранения Кр,Министерство здравоохранения КР,0.999999
79125,Ахмедов Иномжан Абдуллажанович,Ахмедов Иномжан Абдулажанович,0.999999
2405158,Таласбаев Бактыбек Иманкулович,Таласбаев Бактыбек Исманкулович,0.999999
2864232,Мэндсайхан Баярсайхан,баярсайхан мэндсайхан,0.999999
2864231,Баярсайхан Мэндсайхан,Мэндсайхан Баярсайхан,0.999999
2864730,энхсайхан сайхантуяа,Сайхантуяа Энхсайхан,0.999999
2436488,Тилекматова Чинара Асанкожоевна,Тилекматова Чинара Асанкожоева,0.999999
2317394,Шаршебаев Эдил Талантбекович,Шаршенбаев Эдил Талантбекович,0.999999
1558171,Маматов Замирбек Мурзапаашаевич,Маматов Замирбек Музапаашаевич,0.999999
570799,Баярмаа Баярсайхан,Баяраа Баярсайхан,0.999999
2624276,Заварзин Юрий Тимофеевич,Заварин Юрий Тимофеевич,0.999998
2624285,Заварзин Юрий Тимофеевич,Заварин Юрий Тимофеевич,0.999998
2439039,Тохтакунов Марат Талгатович,Тохтахунов Марат Талгатович,0.999997
2335863,СТРИНЖА СЕРГЕЙ СЕРГЕЕВИЧ,Стрижак Сергей Сергеевич,0.999997
2584554,Ульмасов Олимжан Махмутович,Ульмасов Олымжан Махмутович,0.999997
2327876,согласно реестру 38 акционеров,Согласно Реестра Акционеров,0.999997
2584555,Ульмасов Олимжан Махмутович,Ульмасов Олымжан Махмутович,0.999997
2411231,Թեղուտ Ինվեստմենտս Լիմիթիդ,Թեղուտ ինվեստմենտս Լիմիթեդ,0.999997
64219,Абышов Омур Абылмечинович,Абышов Ɵмүр Абылмечинович,0.999997
2411232,Թեղուտ Ինվեստմենտս Լիմիթիդ,Թեղուտ ինվեստմենտս Լիմիթեդ,0.999997
2289989,САтыбалдыев Рахманали Мансурович,Сатыбалдиев Рахманали Мансурович,0.999997
285232,Артыкбаев Субанбек Мамбетжанович,Артыкбаев Суранбек Мамбетжанович,0.999997
2624287,Заварин Юрий Тимофеевич,Заварзин Юрий Тимофеевич,0.999996
1461404,Карыпбек уулу Улукбек,Карыбек уулу Улукбек,0.999995
2250483,Рысбеков Эсен Уланбеколвич,Рысбеков Эсен Уланбекович,0.999994
64231,Абышкаев Данияр Молдакунович,Абышкаев Данияр Молакунович,0.999993
1313572,Халыков Ибрагим Мамажакыпович,Халыков Ибраим Мамажакыпович,0.999993
2864295,Оргил Болд,Болд Оргил,0.999992
2864650,сүх долгор,Долгор Сүх,0.999992
2864627,Mi Dawei,Dawei Mi,0.999992
2865201,Okuno Reeko,Reeko Okuno,0.999992
2863935,Хулан Бат,Бат Хулан,0.999992
2865294,WANG YUFEI,Yufei Wang,0.999992
2863918,Bai Siqin,Siqin Bai,0.999992
2863725,Ta Ala,Ala Ta,0.999992
2865278,цэнд туул,Туул Цэнд,0.999992

In [10]:
# ============================================================
# SAVE SCORED PAIRS
# ============================================================

save_path = "../data/processed/scored_pairs_sample.parquet"

scored_pairs.to_parquet(
    save_path,
    index=False,
)

print(f"Saved to: {save_path}")

Saved to: ../data/processed/scored_pairs_sample.parquet